# Generated by Django 4.0.4 on 2022-05-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candy',
        ),
    ]
