# Generated by Django 4.2.16 on 2024-10-31 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_candy_img_alter_candy_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candy',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('old_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mainApp.product')),
            ],
        ),
    ]
