# Generated by Django 4.2.16 on 2024-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_candy_product_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
