# Generated by Django 4.2.16 on 2024-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_transaction_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='barcode',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='default_barcode_value', max_length=100, null=True, unique=True),
        ),
    ]
