# Generated by Django 4.0.4 on 2022-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='quantity',
            field=models.IntegerField(default=10, verbose_name=100),
            preserve_default=False,
        ),
    ]
