# Generated by Django 4.0.4 on 2022-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0006_alter_candy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='img',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candy',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
